[build]
  command = "npm run build:netlify"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://informed-jh71.onrender.com/api/:splat"
  status = 200
  force = true
